
version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/jayesh/Downloads/docker-frontend-backend-db-master/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - network-frontend
      - network-backend

  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-frontend

  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - network-frontend
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - /home/jayesh/Downloads/LocalDB:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks:
      
      - network-backend


networks:
  network-frontend:
  network-backend:
